mappings:
  PointsOfInterestLayerExtension: WebOfTalent\MappablePointsOfInterest\PointsOfInterestLayerExtension
  POIMapPage: WebOfTalent\MappablePointsOfInterest\POIMapPage
  POIMapPage_Controller: WebOfTalent\MappablePointsOfInterest\POIMapPage_Controller
  PointOfInterest: WebOfTalent\MappablePointsOfInterest\PointOfInterest
  PointsOfInterestLayer: WebOfTalent\MappablePointsOfInterest\PointsOfInterestLayer
  PointsOfInterestAdmin: WebOfTalent\MappablePointsOfInterest\PointsOfInterestAdmin
  NearestPOIPage: WebOfTalent\MappablePointsOfInterest\NearestPOIPage
  NearestPOIPage_Controller: WebOfTalent\MappablePointsOfInterest\NearestPOIPage_Controller
  NearestPOIPage_ControllerTest: WebOfTalent\MappablePointsOfInterest\NearestPOIPage_ControllerTest
  PointsOfInterestLayerTest: WebOfTalent\MappablePointsOfInterest\PointsOfInterestLayerTest
  PointsOfInterestLayerTestObjectTO: WebOfTalent\MappablePointsOfInterest\PointsOfInterestLayerTestObjectTO
  PointsOfInterestAdminTest: WebOfTalent\MappablePointsOfInterest\PointsOfInterestAdminTest
  OSMPointOfInterestExtensionTest: WebOfTalent\MappablePointsOfInterest\OSMPointOfInterestExtensionTest
  OSMTestPageTO: WebOfTalent\MappablePointsOfInterest\OSMTestPageTO
  PointsOfInterestLayerExtensionTest: WebOfTalent\MappablePointsOfInterest\PointsOfInterestLayerExtensionTest
  POILayerExtensionPageTO: WebOfTalent\MappablePointsOfInterest\POILayerExtensionPageTO
  POIMapPageTest: WebOfTalent\MappablePointsOfInterest\POIMapPageTest
  PointOfInterestTest: WebOfTalent\MappablePointsOfInterest\PointOfInterestTest
  NearestPOIPageTest: WebOfTalent\MappablePointsOfInterest\NearestPOIPageTest
  ImagePointOfInterestExtensionTest: WebOfTalent\MappablePointsOfInterest\ImagePointOfInterestExtensionTest
  ImagePotTestPageTO: WebOfTalent\MappablePointsOfInterest\ImagePotTestPageTO
